<%@ Page Language="C#" AutoEventWireup="true"
    CodeBehind="ShowStudents.aspx.cs"
    Inherits="smart_school_management_system.ShowStudents" %>

<!DOCTYPE html>
<html>
<head runat="server">
    <title>Show Students</title>

    <style>
        body {
            font-family: 'Segoe UI', Tahoma, sans-serif;
            background: linear-gradient(135deg, #fdfbfb, #ebedee);
        }

        .container {
            width: 90%;
            margin: 50px auto;
            background-color: #ffffff;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0px 10px 25px rgba(0,0,0,0.2);
            text-align: center;
        }

        h2 {
            color: #2c3e50;
            margin-bottom: 20px;
        }

        .grid {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .grid th {
            background-color: #3498db;
            color: white;
            padding: 12px;
            text-align: center;
        }

        .grid td {
            padding: 10px;
            border: 1px solid #ccc;
            text-align: center;
        }

        .grid tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .grid input[type="text"] {
            width: 95%;
            padding: 5px;
        }

        .btn {
            margin-top: 20px;
            padding: 10px 25px;
            font-size: 15px;
            border-radius: 6px;
            border: none;
            cursor: pointer;
            background-color: #27ae60;
            color: white;
            transition: all 0.3s ease;
        }

        .btn:hover {
            background-color: #219150;
            transform: translateY(-2px);
        }

        .msg {
            margin-top: 15px;
            font-weight: bold;
        }
    </style>

</head>
<body>
<form id="form1" runat="server">

<div class="container">

<h2>Student List</h2>

<asp:GridView ID="gvStudents" runat="server"
    CssClass="grid"
    AutoGenerateColumns="False"
    DataKeyNames="StudentID"
    AutoGenerateEditButton="True"
    AutoGenerateDeleteButton="True"
    OnRowEditing="gvStudents_RowEditing"
    OnRowCancelingEdit="gvStudents_RowCancelingEdit"
    OnRowUpdating="gvStudents_RowUpdating"
    OnRowDeleting="gvStudents_RowDeleting">

    <Columns>

        <asp:BoundField DataField="StudentID"
            HeaderText="ID"
            ReadOnly="True" />

        <asp:TemplateField HeaderText="Name">
            <ItemTemplate><%# Eval("Name") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtName" runat="server"
                    Text='<%# Bind("Name") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Email">
            <ItemTemplate><%# Eval("Email") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtEmail" runat="server"
                    Text='<%# Bind("Email") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Phone">
            <ItemTemplate><%# Eval("Phone") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtPhone" runat="server"
                    Text='<%# Bind("Phone") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Class">
            <ItemTemplate><%# Eval("Class") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtClass" runat="server"
                    Text='<%# Bind("Class") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Gender">
            <ItemTemplate><%# Eval("Gender") %></ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtGender" runat="server"
                    Text='<%# Bind("Gender") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

    </Columns>
</asp:GridView>

<asp:Label ID="lblMsg" runat="server"
    ForeColor="Green"
    CssClass="msg"></asp:Label>

<asp:Button runat="server"
    Text="Back to Dashboard"
    CssClass="btn"
    PostBackUrl="AdminDashboard.aspx" />

</div>

</form>
</body>
</html>
